# Generated by Django 2.0.2 on 2018-02-26 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('acountry', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bornAt', models.DateField()),
                ('diedAt', models.DateField(blank=True, default=None, null=True)),
                ('bio', models.TextField(null=True)),
                ('followers', models.IntegerField(null=True)),
                ('follow', models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('publishedAt', models.DateField()),
                ('rate', models.FloatField(default=0, null=True)),
                ('desc', models.TextField()),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapeZone.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('favorite_Category', models.ManyToManyField(blank=True, default=None, null=True, related_name='fav', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRatePerBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book_rate', to='escapeZone.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_catagory',
            field=models.ManyToManyField(to='escapeZone.Catagory'),
        ),
        migrations.AddField(
            model_name='book',
            name='read',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='wish',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='wish', to=settings.AUTH_USER_MODEL),
        ),
    ]
